version: "3"

services:
  tomcat:
    image: tomcat:9.0-jdk8-corretto
    container_name: tomcat9
    ports:
      - "8080:8080"
      - "1812:1812/udp"
      - "1813:1813/udp"
      - "8000:8000"
    restart: unless-stopped
    tty: true
    volumes:
      - ./webapps:/usr/local/tomcat/webapps/
    networks: 
      - nginx-network-default
networks:
  nginx-network-default:
    external: true