version: '3'

services:
    db:
        image: postgres:15
        volumes:
            - joplindb:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=POSTGRES_PASSWORD
            - POSTGRES_USER=POSTGRES_USER
            - POSTGRES_DB=POSTGRES_DATABASE
    app:
        image: joplin/server:latest
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=https://yourwebsite.com
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=POSTGRES_PASSWORD
            - POSTGRES_DATABASE=POSTGRES_DATABASE
            - POSTGRES_USER=POSTGRES_USER
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
            - MAILER_ENABLED=1
            - MAILER_HOST=smtp.gmail.com
            - MAILER_PORT=465
            - MAILER_SECURE=1
            - MAILER_AUTH_USER=you@yourdomain.com
            - MAILER_AUTH_PASSWORD=3m@1lPa55w0rD
            - MAILER_NOREPLY_NAME=JoplinServer
            - MAILER_NOREPLY_EMAIL=you@yourdomain.com
            
volumes:
  joplindb:
