version: '3.3'
services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ./config:/config
    ports:
      - 9091:9091
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - TZ=Asia/Kolkata
    depends_on:
      - redis
    networks:
      - nginx-network-default

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./redis:/data
    expose:
      - 6379
    ports:
      - "6379:6379"
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
    networks:
      - nginx-network-default
networks:
  nginx-network-default:
    external: true
