services:
  guacamole:
    image: jwetzell/guacamole
    container_name: guacamole
    volumes:
      - guacamole-data:/config
    ports:
      - 7878:8080
    networks:
      - nginx-network-default
volumes:
  guacamole-data:
networks:
  nginx-network-default:
    external: true
