version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '780:80'
      - '7443:443'
      - '722:22'
      - '7587:587'
      - '8929:8929'
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    shm_size: '256m'
