services:
  db:
    container_name: mssql_container
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Passw0rd.
    ports:
      - "1435:1433"
    volumes:
      - mssqlvolume:/var/opt/mssql/data
volumes:
  mssqlvolume:
